# Default values for harvester.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  secret: "panda-secrets"

harvester:
  # enable harvester
  enabled: true
  # container image and tag
  image:
    tag: "v0.7.2"
    # tag: "v0.6.1"
    # tag: "master"

  # PV with selector support
  #persistentvolume:
  #    selector: false

  # Experiment
  experiment: ""

  # http/s proxy if containers need it to access external services
  #httpProxy: "http://proxy.sdcc.bnl.local:3128"
  #httpsProxy: "http://proxy.sdcc.bnl.local:3128"

  # run containers with no-root PID e.g. for OKD
  #noRoot: true
  
  resources:
    limits:
      cpu: 4000m
      memory: 16Gi
      ephemeral-storage: "50Gi"
    requests:
      cpu: 2000m
      memory: 8Gi
      ephemeral-storage: "30Gi"

mariadb:
  # enable database
  enabled: true

  # PV with selector support
  #persistentvolume:
  #    selector: false

  # Security context to fix permission issues with bitnami/mariadb (runs as UID 1001)
  podSecurityContext:
    fsGroup: 1001

  image:
      repository: bitnami/mariadb
      pullPolicy: IfNotPresent
      # tag: "10.11.11"
      tag: "latest"
 
  resources:
    limits:
      cpu: 4000m
      memory: 16Gi
      ephemeral-storage: "50Gi"
    requests:
      cpu: 2000m
      memory: 4Gi
      ephemeral-storage: "30Gi"
