# Default values for idds.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

rest:
  replicaCount: 2
  iddsServer: cms-panda-idds-test.cern.ch

  ingress:
    enabled: true
    hosts:
      - domain: cern.ch
        hostOverride: cms-panda-idds-test.cern.ch
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: "default"
        hosts:
          - domain: cern.ch
            hostOverride: cms-panda-idds-test.cern.ch
